---
- name: Kubelet | Copy executables of kubelet, kubectl, kubeadm
  ansible.builtin.copy:
    src: "bin/{{ item }}"
    dest: /usr/local/bin
    mode: "0744"
  with_items:
    - kubeadm
    - kubectl
    - kubelet

- name: Kubelet | Create kubelet service directory
  ansible.builtin.file:
    path: /etc/systemd/system/kubelet.service.d/
    state: directory
    owner: root
    group: root
    mode: "0600"

- name: Kubelet | Copy kubelet systemd service
  ansible.builtin.copy:
    src: service/kubelet.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: "0600"

- name: Kubelet | Copy kubelet systemd service directory
  ansible.builtin.copy:
    src: service/kubelet.service.d
    dest: /etc/systemd/system/kubelet.service.d/
    owner: root
    group: root
    mode: "0600"

- name: Kubelet | Restart kubelet systemd service
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: true
    daemon_reload: true
