---
- name: Containerd | Create containerd directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    recurse: true
  with_items:
    - /etc/containerd

- name: Containerd | Copy containerd executable
  ansible.builtin.copy:
    src: 'tar/{{ item }}'
    dest: /usr/local/ # Containerd tarfile containes path `bin`
  with_items:
    - containerd-2.1.4-linux-amd64.tar.gz

- name: Containerd | Copy containerd config file of ECS
  ansible.builtin.copy:
    src: etc/containerd/config-ecs.toml
    dest: /etc/containerd/config.toml
    backup: yes
#   when:
#     machine_type == 'CPU'

# - name: Containerd | Copy containerd config file of GPU ECS
#   ansible.builtin.copy:
#     src: etc/containerd/config-gpu.toml
#     dest: /etc/containerd/config.toml
#     backup: yes
#   when:
#     machine_type == 'GPU'

- name: Containerd | Copy containerd systemd service
  ansible.builtin.copy:
    src: service/containerd.service
    dest: /etc/systemd/system

- name: Containerd | Restart containerd systemd service
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: true
    daemon_reload: true